remote_theme: BDHU/minimalist
title: Matthew Bream
description: 3rd Year Cyber Security Student at University of Warwick \n test
color-scheme: auto
logo: ./assets/Profile_Pic.png
show_downloads: false

sidebar:
  - name: LinkedIn
    link: https://www.linkedin.com/in/matthew-bream/
  - name: Github
    link: https://github.com/ATinyFish3
  - name: CV
    link: ./files/CURRICULUM-VITAE.html
  
