remote_theme: BDHU/minimalist
title: Matthew Bream
description: Cyber Security Student at University of Warwick
color-scheme: auto
logo: https://media-exp1.licdn.com/dms/image/C4D03AQGP5SgaQR_qHQ/profile-displayphoto-shrink_200_200/0/1621007688144?e=1670457600&v=beta&t=2H3SFByL_Njv2-TuWK7el-q5VPOje72Iy_rlFJDDfrk
show_downloads: false

sidebar:
  - name: LinkedIn
    link: https://www.linkedin.com/in/matthew-bream-5a1011212/
