remote_theme: BDHU/minimalist
title: Matthew Bream
description: Cyber Security Student at University of Warwick
color-scheme: auto
logo: ./assets/MB.png
show_downloads: false

sidebar:
  - name: LinkedIn
    link: https://www.linkedin.com/in/matthew-bream-5a1011212/
  - name: Github
    link: https://github.com/ATinyFish3
  - name: CV
    link: ./files/testCV.pdf
  
